<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'RateLimit\Module'                        => __DIR__ . '/Module.php',
    'RateLimit\Controller\IndexController' => __DIR__ . '/src/RateLimit/Controller/IndexController.php',
    'RateLimitTest\Framework\TestCase'        => __DIR__ . '/tests/RateLimit/Framework/TestCase.php',
    'RateLimitTest\SampleTest'                => __DIR__ . '/tests/RateLimit/SampleTest.php',
);
