<?php
$liClass = $this->page->isActive() ? 'active' : '';
$extraAttributes = '';

if ($this->page->hasPages()) {
    if ($this->depth == 0) {
        $liClass .= ' dropdown';
        $extraAttributes = 'class="dropdown-toggle" data-toggle="dropdown"';
    } else {
        $liClass .= ' dropdown-submenu';
    }
}

?>

<li class="<?php echo $liClass; ?>">
    <a href="<?php echo $this->page->getHref(); ?>"
	<?php echo $extraAttributes; ?>>
	<span class="<?php echo $page->icon ?: ''; ?>" ></span>&nbsp;
	<?php echo $this->translate($this->page->getLabel()); ?> <?php if($this->page->hasPages() && $this->depth == 0): ?><b
		class="caret"></b><?php endif; ?></a>
		
    <?php if($this->page->hasPages()): ?>
    
    <ul class="dropdown-menu">
    
    <?php foreach ($this->page->getPages() as $subPage): ?>
    
        <?php 
            $display = true;
            if($subPage->resource){
                if(!$this->isAllowed($subPage->resource, $subPage->privilege)){
                    $display = false;
                }
            }
            if($display)
                echo $this->partial('partial/navigation-menu-level', array('page' => $subPage, 'depth' => $this->depth + 1));
        ?>
    
    <?php endforeach; ?>
    
    </ul>
    
    <?php endif; ?>
		
</li>