<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DotUser\Module'                        => __DIR__ . '/Module.php',
    'DotUser\Controller\UserController' => __DIR__ . '/src/DotUser/Controller/UserController.php',
    'DotUserTest\Framework\TestCase'        => __DIR__ . '/tests/DotUser/Framework/TestCase.php',
    'DotUserTest\SampleTest'                => __DIR__ . '/tests/DotUser/SampleTest.php',
);
