<?php 

$title = "Change Email";
$this->headtitle($title);
?>

<h1><?php echo $this->translate($this->escapehtml($title)); ?></h1>
<div class="form-container">
<?php 
$form = $this->form;
$form->setAttribute('action', $this->url('zfcuser/change-email'));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form');
$form->setAttribute('role', 'form');
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
<?php
$form->get('email')->setAttribute('class', 'form-control');
echo $this->formRow($form->get('email'));
?>
</div>
<div class="form-group">
<?php
$form->get('password')->setAttribute('class', 'form-control');
echo $this->formRow($form->get('password'));
?>
</div>

<?php 
$form->get('submit')->setAttribute('class', 'btn btn-default');
echo $this->formsubmit($form->get('submit'));
?>

<?php echo $this->form()->closeTag(); ?>
</div>