<div style="padding-bottom: 10px;">
    <div style="float:left; padding-right:16px;"><?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?></div>
    <h3><?php echo $this->translate('Hello'); ?>, <?php echo $this->zfcUserDisplayName() ?>!</h3>
    <a href="<?php echo $this->url('zfcuser/change-email') ?>">[<?php echo $this->translate('Change Email'); ?>]</a><br>
    <a href="<?php echo $this->url('zfcuser/logout') ?>">[<?php echo $this->translate('Sign Out'); ?>]</a>
    <div style="clear:both;"></div>
</div>

<?php 
$detailsForm = $this->userDetailsForm;
$changePasswordForm = $this->changePasswordForm;

?>

<div class="row">
    <div class="col-md-7">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Edit details') ?></h3>
            </div>
            <div class="panel-body">
                <div style="padding: 10px 50px 10px 10px;">
                <?php 
                    echo $this->partial('dot-user/partials/update-form.phtml', array('form' => $detailsForm));
                ?>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-5">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Change Password') ?></h3>
            </div>
            <div class="panel-body">
                <?php 
                    echo $this->partial('dot-user/partials/change-password.phtml', array('form' => $changePasswordForm));
                ?>
            </div>
        </div>
    </div>
</div>