<?php 

$title = "Forgot your password?";
$this->headtitle($title);
?>

<h1><?php echo $this->translate($this->escapehtml($title)); ?></h1>
<p>Input your email address you've registered with. You will receive an email with a reset password link</p>
<div class="form-container">
<form action="/user/recovery" method="post" class="form" role="form">
    <div class="form-group">
        <label>
            <span>Email</span>
            <input type="email" name="recovery_email" class="form-control" placeholder="Your Email..." />
        </label>
    </div>
    <button type="submit" class="btn btn-default" >Send</button>
</form>
</div>