<?php 

$title = 'Reset Password';
$this->headtitle($title);
?>

<h1><?php echo $this->translate($this->escapehtml($title)); ?></h1>
<div class="form-container">
<?php 
$form = $this->form;
$form->setAttribute('action', $this->url('zfcuser/reset-password'));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form');
$form->setAttribute('role', 'form');
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
<?php
$form->get('password')->setAttribute('class', 'form-control');
echo $this->formRow($form->get('password'));
?>
</div>
<div class="form-group">
<?php
$form->get('password_verify')->setAttribute('class', 'form-control');
echo $this->formRow($form->get('password_verify'));
?>
</div>

<div class="form-group">
<?php
$form->get('email')->setAttribute('class', 'form-control');
if($this->email)
    $form->get('email')->setAttribute('value', $this->email);
echo $this->formRow($form->get('email'));
?>
</div>

<div class="form-group">
<?php
$form->get('token')->setAttribute('class', 'form-control');
if($this->token)
    $form->get('token')->setAttribute('value', $this->token);
echo $this->formRow($form->get('token'));
?>
</div>

<?php 
$form->get('submit')->setAttribute('class', 'btn btn-default');
echo $this->formsubmit($form->get('submit'));
?>

<?php echo $this->form()->closeTag(); ?>

</div>

