<?php 

$title = 'Sign Up';
$this->headtitle($title);
?>

<h1><?php echo $this->translate($this->escapehtml($title)); ?></h1>
<div class="form-container">
<?php
if (!$this->enableRegistration) {
    echo $this->translate('Registration is disabled');
    return;
}
$form = $this->registerForm;
$details = $this->registerForm->get('details');
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form');
$form->setAttribute('role', 'form');
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
<?php
$form->get('username')->setAttribute('class', 'form-control');
echo $this->formRow($form->get('username'));
?>
</div>
<div class="form-group">
<?php
$form->get('email')->setAttribute('class', 'form-control');
echo $this->formRow($form->get('email'));
?>
</div>
<div class="form-group">
<?php
$form->get('password')->setAttribute('class', 'form-control');
echo $this->formRow($form->get('password'));
?>
</div>
<div class="form-group">
<?php
$form->get('passwordVerify')->setAttribute('class', 'form-control');
echo $this->formRow($form->get('passwordVerify'));
?>
</div>

<div class="form-group">
<?php
$details->get('firstName')->setAttribute('class', 'form-control');
echo $this->formRow($details->get('firstName'));
?>
</div>

<div class="form-group">
<?php
$details->get('lastName')->setAttribute('class', 'form-control');
echo $this->formRow($details->get('lastName'));
?>
</div>

<div class="form-group">
<?php
$form->get('captcha')->setAttribute('class', 'form-control');
echo $this->formRow($form->get('captcha'));
?>
</div>

<?php 
$form->get('submit')->setAttribute('class', 'btn btn-default');
echo $this->formButton($form->get('submit')); 
?>

<?php if ($this->redirect): ?>
    <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
<?php endif ?>
<?php echo $this->form()->closeTag(); ?>

</div>