<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('DotKernel '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/dot-main.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/logo.png') ?>" alt="DotKernel"/>&nbsp;<?php echo $this->translate('DotKernel') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <?php echo $this->navigation('navigation')->menu()->setPartial(array('partial/navigation.phtml', 'Application')); ?>
                       
                    <?php
                        //displays sign in widget
                        //echo $this->navbar_signin;
                    ?>
                    
                </div><!--/.nav-collapse -->
                
            </div>
        </nav>

        <div class="container">
            <?php 
                $namespaces = array('error'=>'danger','success'=>'success','info'=>'info','default'=>'warning');
                foreach ($namespaces as $namespace => $alert)
                {
                    $flashMessages = $this->flashmessenger()->render($namespace);
                    if(!empty($flashMessages))
                    {?>
                        <div id="dot-alert" class="alert alert-<?=$alert ?>" data-alert="alert">
                            <a class="close" data-dismiss="alert">x</a>
                            <?=$flashMessages?>
                        </div>    
                    <?php
                    }
                }
            ?>
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2009 - <?php echo date('Y') ?> by Dotboost Technologies Inc. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
