<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DotLimit\Module'                        => __DIR__ . '/Module.php',
    'DotLimit\Controller\IndexController' => __DIR__ . '/src/DotLimit/Controller/IndexController.php',
    'DotLimitTest\Framework\TestCase'        => __DIR__ . '/tests/DotLimit/Framework/TestCase.php',
    'DotLimitTest\SampleTest'                => __DIR__ . '/tests/DotLimit/SampleTest.php',
);
