<?php 
$form = $this->form;
$form->setAttribute('action', $this->url('zfcuser/change-password'));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form');
$form->setAttribute('role', 'form');
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
<?php
$form->get('old_password')->setAttribute('class', 'form-control');
echo $this->formRow($form->get('old_password'));
?>
</div>
<div class="form-group">
<?php
$form->get('new_password')->setAttribute('class', 'form-control');
echo $this->formRow($form->get('new_password'));
?>
</div>
<div class="form-group">
<?php
$form->get('new_password_verify')->setAttribute('class', 'form-control');
echo $this->formRow($form->get('new_password_verify'));
?>
</div>

<?php 
$form->get('submit')->setAttribute('class', 'btn btn-default');
echo $this->formsubmit($form->get('submit'));
?>

<?php echo $this->form()->closeTag(); ?>