<?php 
$form = $this->form;
$form->setAttribute('action', $this->url('zfcuser'));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form');
$form->setAttribute('role', 'form');
$form->prepare();

echo $this->form()->openTag($form);

foreach ($form as $element)
{
    if($element->getName() === 'submit') continue;
    
    echo $this->partial('dot-user/partials/update-form-element.phtml', array('element' => $element, 'depth' => 0));
}

?>

<?php 

$form->get('submit')->setAttribute('class', 'btn btn-default');
echo $this->formsubmit($form->get('submit'));
?>

<?php echo $this->form()->closeTag(); ?>