<?php

$element = $this->element;
$depth = $this->depth;

if(!$element instanceof \Zend\Form\Fieldset)
{
    $element->setAttribute('class', 'form-control');
    ?>
    <div class="form-group">
        <?php echo $this->formrow($element); ?>
    </div>
    <?php
}
else{
    foreach ($element->getElements() as $subElement)
    {
        echo $this->partial('dot-user/partials/update-form-element.phtml', array('element' => $subElement, 'depth' => $depth + 1));
    }
}

?>