<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DotBase\Module'                        => __DIR__ . '/Module.php',
    'DotBase\Controller\IndexController' => __DIR__ . '/src/DotBase/Controller/IndexController.php',
    'DotBaseTest\Framework\TestCase'        => __DIR__ . '/tests/DotBase/Framework/TestCase.php',
    'DotBaseTest\SampleTest'                => __DIR__ . '/tests/DotBase/SampleTest.php',
);
